// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrzehvyocruwqrjzrxse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyemVodnlvY3J1d3FyanpyeHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0Njc1MjcsImV4cCI6MjA3ODA0MzUyN30.5_N0fyu3mhOm4G6THkx4X3olde85vWWFeV57cBzsFas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});